version: '3.3'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  prod:
    container_name: booking-api-container
    image: kushalgaur123/booking-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge
